### PR TITLE
fix(runtime): should calculate `initial_chunks` correctly

### LINKED ISSUE #4019: the runtime module of multiple entries would override each other when they have the same name
### System Info

.

### Details

The content of https://github.com/hyf0/rspack-css-only-chunk-runtime-error/blob/main/rspack-dist/build-runtime.js is for the entry `index2.js`.

image
image

Missing chunk info for chunk id `vendor`.

See https://github.com/hyf0/rspack-css-only-chunk-runtime-error

### Reproduce link

_No response_

### Reproduce Steps

.

### PR DESCRIPTION
**Pull request by hyf0**
## Summary

Fixes #4019

## Test Plan

Added

### CODE REVIEW

File: crates/rspack_core/src/chunk.rs [hunk 1]
```diff
@@ -223,15 +223,19 @@ impl Chunk {
   }
 
   pub fn get_all_async_chunks(&self, chunk_group_by_ukey: &ChunkGroupByUkey) -> HashSet<ChunkUkey> {
+    use rustc_hash::FxHashSet;
```
Comment (underfin) [inline crates/rspack_core/src/chunk.rs:226]: The file already import `FxHashSet` as `HashSet`

**Comment by hyf0** [comment]
!canary

File: crates/rspack_core/src/chunk.rs (hunk 1 above)
Comment (hyf0) [reply crates/rspack_core/src/chunk.rs:226]: I don't want to run CI again. Let's keep it now.

**Review by underfin — APPROVED** [review]
