### PR TITLE
fix: :bug: windows absolute should not be considered as scheme

### LINKED ISSUE #2558: [Bug Report]: windows build error：System cannot find the specified path (os error 3)
### System Info

* System
  * OS: Windows 10 19043.2006
  * CPU: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz   2.30 GHz
  * Memory: 16.0 GB
  * Shell: Powershell
* Binaries:
  * Node.js: v16.18.0
  * npm: 8.19.2
  * yarn: 1.22.19
  * pnpm: 7.29.1

### Details

img_v2_9fe4f13e-4b4e-49ac-b7b6-dfa71391ebeg

### Reproduce link

https://github.com/web-infra-dev/modern.js

### Reproduce Steps

1. pnpm install 
2. pnpm prepare
3. cd tests/integration/builder-rspack
4. pnpm run dev

### PR DESCRIPTION
**Pull request by JSerFeng**
## Summary

close #2558 

## Types of changes

- [ ] Docs change / Dependency upgrade
- [x] Bug fix
- [ ] New feature / Improvement
- [ ] Refactoring
- [ ] Breaking change

## Checklist

- [x] I have added changeset via `pnpm run changeset`.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: crates/rspack_core/src/normal_module_factory.rs [hunk 1]
```diff
@@ -84,8 +84,8 @@ impl NormalModuleFactory {
       .ok();
     let plugin_driver = &self.plugin_driver;
 
-    // with scheme
-    let resource_data = if let Some(scheme) = scheme {
+    // with scheme, windows absolute path is considered scheme by `url`
+    let resource_data = if let Some(scheme) = scheme && !Path::is_absolute(Path::new(specifier)) {
```
Comment (hardfist) [inline crates/rspack_core/src/normal_module_factory.rs:88]: we should add a test for this

**Review by hardfist — APPROVED** [review]
