### PR TITLE
fix: css modules ident escape

### LINKED ISSUE #6641: [Bug]: v0.7.0 CSS modules styles all missing
### System Info

  System:
    OS: macOS 14.4
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900KF
    Memory: 10.29 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.1 - /usr/local/bin/node
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 9.0.4 - /usr/local/bin/pnpm
    Watchman: 2024.05.06.00 - /usr/local/bin/watchman

### Details

All css styles missing:

截屏2024-05-28 18 30 01

### Reproduce link

_No response_

### Reproduce Steps

see above.

### PR DESCRIPTION
**Pull request by ahabhgk**
## Summary

fix #6641

## Checklist

- [x] Tests updated (or not required).
- [x] Documentation updated (or not required).

### CODE REVIEW

File: webpack-test/configCases/css/default-exports-parser-options/index.js [hunk 1]
```diff
@@ -3,16 +3,16 @@ import style2 from "./style.module.css?default";
 import { foo } from "./style.module.css?named";
 
 it("should able to import with default and named exports", () => {
-	expect(style1.default).toEqual(nsObj({ foo: '-__style_module_css_namespace-foo' }));
-	expect(style1.foo).toEqual("-__style_module_css_namespace-foo");
-	expect(style2).toEqual(nsObj({ foo: '-__style_module_css_default-foo' }));
-	expect(foo).toEqual("-__style_module_css_named-foo");
+	expect(style1.default).toEqual(nsObj({ foo: '-_style_module_css_namespace-foo' }));
```
Comment (ahabhgk) [inline webpack-test/configCases/css/default-exports-parser-options/index.js:6]: now this is exact the same as webpack 😅

**Review by JSerFeng — APPROVED** [review]
