### PR TITLE
fix(css): remove trailing space at classname

### LINKED ISSUE #2594: [Bug Report]: Why is there an extra space after the hash value？
### System Info

System:
    OS: macOS 13.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 4.17 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.21.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.18 - /usr/local/bin/npm

### Details

After I set `builtins.css.modules.localIdentName` to `'[local]--[hash:6]'`, I noticed there was a weird space after the hash.
image

### Reproduce link

https://github.com/dingff/rspack-template

### Reproduce Steps

1. yarn dev

### PR DESCRIPTION
**Pull request by nieyuyao**
## Summary

try fix #2594 

## Types of changes

- [ ] Docs change / Dependency upgrade
- [x] Bug fix
- [ ] New feature / Improvement
- [ ] Refactoring
- [ ] Breaking change

## Checklist

- [x] I have added changeset via `pnpm run changeset`.
- [x] I have added tests to cover my changes.

### CODE REVIEW

File: crates/rspack_plugin_css/src/utils.rs [hunk 1]
```diff
@@ -101,8 +101,14 @@ pub fn css_modules_exports_to_string(
...
-      .collect::<Vec<_>>()
-      .join(" + ");
+      .collect::<Vec<_>>();
+    let mut n = 1;
+    // insert space between each classname
+    while n < class_names.len() {
+      class_names.insert(n, String::from("\" \""));
+      n += 2;
+    }
+    let content = class_names.join(" + ");
```
Comment (ahabhgk) [inline crates/rspack_plugin_css/src/utils.rs:111]:
```suggestion
    let content = class_names.join(" + \" \" + ");
```

**Review by ahabhgk — CHANGES_REQUESTED** [review]

**Review by ahabhgk — APPROVED** [review]
Thanks!
