### PR TITLE
fix: do not stopped when decode base64 failed

### LINKED ISSUE #4258: error[internal]: Base64Error
### System Info

System:
    OS: macOS 13.5.1
    CPU: (8) x64 Apple M1
    Memory: 43.78 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.18.3/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.3/bin/npm
    pnpm: 7.30.0 - ~/Library/pnpm/pnpm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 117.0.5938.92
    Safari: 16.6
  npmPackages:
    @rspack/cli: 0.3.4 => 0.3.4 

### Details

image

### Reproduce link

https://github.com/jeromehan/vue3-rspack-demo

### Reproduce Steps

1. npm run dev

### PR DESCRIPTION
**Pull request by bvanjoi**
Fixes #4258

This issue arises from the inconsistent behavior between ﻿`Buffer.from(xxx, 'base64’)` in node and ﻿`decode` in `﻿base64_simd`.

In this PR, I introduce the following modifications:
- If the base64 decoding is successful, the decoded buffer is returned.
- Otherwise, the original code is returned to continue the process. This design is intended to allow developers to handle such cases in their own ways. And I think this approach aligns with the logic of webpack.

### CODE REVIEW

File: crates/rspack_plugin_schemes/src/data_uri.rs [hunk 1]
```diff
@@ -58,7 +57,10 @@ impl Plugin for DataUriPlugin {
       let body = captures.get(4).expect("should have data uri body").as_str();
       let is_base64 = captures.get(3).is_some();
       if is_base64 && let Some(cleaned) = rspack_base64::clean_base64(body) {
-        return Ok(Some(Content::Buffer(rspack_base64::decode_to_vec(cleaned.as_bytes()).map_err(|e| internal_error!(e.to_string()))?)))
+        return match rspack_base64::decode_to_vec(cleaned.as_bytes()) {
+          Ok(buffer) => Ok(Some(Content::Buffer(buffer) )),
+          Err(_) => Ok(Some(Content::String(resource_data.resource.to_string())))
```
Comment (bvanjoi) [inline crates/rspack_plugin_schemes/src/data_uri.rs:62]: ﻿`to_string` is not efficient. I suggest returning a `﻿&str` would be more appropriate.

**Review by ahabhgk — APPROVED** [review]
