### PR TITLE
fix: use string as key for resolve.by_dependency

### LINKED ISSUE #4432: Panicked when use ... wildcard in mainFields or conditionNames
### System Info

  System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 366.08 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Yarn: 1.22.19 - ~/Library/Application Support/fnm/node-versions/v16.19.1/installation/bin/yarn
    npm: 8.19.3 - ~/Library/Application Support/fnm/node-versions/v16.19.1/installation/bin/npm
    pnpm: 8.9.2 - ~/Library/Application Support/fnm/node-versions/v16.19.1/installation/bin/pnpm
  Browsers:
    Chrome: 118.0.5993.88
    Safari: 16.6
  npmPackages:
    @rspack/cli: ^0.3.8 => 0.3.8 

### Details

Rspack build panicked when use ... wildcard in mainFields or conditionNames:

image

```js
const config = {
  resolve: {
    mainFields: ["...", "custom"],
    conditionNames: ["...", "custom"],
  },
};
```

### Reproduce link

https://github.com/chenjiahan/rspack-repro-main-fields-wildcard

### Reproduce Steps

pnpm run build

### PR DESCRIPTION
**Pull request by bvanjoi**
Fixes #4432

There has `undefined` and `default` field in `resolve.byDependency` in webpack, so let us change it to `Map<String, Resolve>`

### CODE REVIEW

File: crates/rspack_core/src/options/resolve.rs [hunk 1]
```diff
@@ -115,11 +115,13 @@ impl Resolve {
   }
 }
 
+type DependencyCategoryStr = String;
```
Comment (h-a-n-a) [inline crates/rspack_core/src/options/resolve.rs:118]: I would like to suggest using `Cow<'static, str>` in this case.

**Review by h-a-n-a — APPROVED** [review]

**Review by ahabhgk — APPROVED** [review]
