### PR TITLE
fix(@rspack/core): js Compilation instance is not recreated as expected when rebuilding on watch/serve mode

### LINKED ISSUE #5398: taps inflation on serve mode
### System Info

```

  System:
    OS: macOS 14.3
    CPU: (12) arm64 Apple M2 Max
    Memory: 123.84 MB / 32.00 GB
    Shell: 3.7.0 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.10.0 - ~/.managed/n/bin/node
    npm: 10.2.3 - ~/.managed/n/bin/npm
    pnpm: 8.14.2 - ~/.managed/n/bin/pnpm
    bun: 1.0.22 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 17.3
  npmPackages:
    @rspack/cli: canary => 0.5.1-canary-38ebbd3-20240118010407 
    @rspack/core: canary => 0.5.1-canary-38ebbd3-20240118010407 

```

Also produced with:
- 0.5.1 
- nightly (0.5.1)
- 0.5.2-canary-6f90fc7-20240123030502 #5400

Not produced with:
- 0.5.0

### Details

image

### Reproduce link

https://github.com/xc2/rspack-hooks-repro

### Reproduce Steps

```js
// a plugin in js
const plugin = {
    apply(compiler) {
        const name = 'plugin-xx';
        compiler.hooks.compilation.tap(name, (compilation) => {
            compilation.hooks.optimizeChunkModules.tap(name, () => {
                console.log('optimizeChunkModules called');
            })
            
            console.log('optimizeChunkModules taps:', compilation.hooks.optimizeChunkModules.taps.filter(tap => tap.name === name).length);
        })
    }
}
```

### Steps

- Run serve mode
- See once `optimizeChunkModules called` following `optimizeChunkModules taps: 1`
- Modify source codes like `src/index.js`
- See double `optimizeChunkModules called` following `optimizeChunkModules taps: 2`
- Modify source codes like `src/index.js`
- See triple `optimizeChunkModules called` following `optimizeChunkModules taps: 3`

### Expected

- Always see once `optimizeChunkModules called` following `optimizeChunkModules taps: 1` after every source change.

### More

I use `compiler.hooks.compilation` and `compilation.hooks.optimizeChunkModules` just for instance - seems that this issue applies to not only these hooks.

### PR DESCRIPTION
**Pull request by xc2**
## Summary

fixes #5398

The recent modification disabled the `Compiler#newCompilation` function from being called when there are no taps on the `thisCompilation` hook. See: https://github.com/web-infra-dev/rspack/pull/5202

As a result, every rebuilding now share a single instance of `Compilation`, which is not expected as it leads to the problem described in #5398.

## Require Documentation?

- [x] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

File: packages/rspack/src/Compiler.ts [hunk 1]
```diff
@@ -643,7 +643,8 @@ class Compiler {
 			succeedModule: this.compilation.hooks.succeedModule,
 			stillValidModule: this.compilation.hooks.stillValidModule,
 			buildModule: this.compilation.hooks.buildModule,
-			thisCompilation: this.hooks.thisCompilation,
+			// various of hooks are called inside `#newCompilation`, we shouldn't prevent `#newCompilation` from calling even when `thisCompilation` is not tapped.
```
Comment (h-a-n-a) [inline packages/rspack/src/Compiler.ts:646]:
```suggestion
			// various of hooks are called inside `#newCompilation`, we shouldn't prevent `#newCompilation` from calling even when `thisCompilation` is not tapped. 
		 // issue: https://github.com/web-infra-dev/rspack/issues/5398
```

**Review by h-a-n-a — APPROVED** [review]

**Comment by xc2** [comment]
!canary
