### PR TITLE
fix: modify Configuration type to support MultiRspackOptions

### LINKED ISSUE #3607: defineConfig MultiplyCompiler Type not export.
### System Info

- 

### Details

MultiplyCompiler Type did not export, caused ts error. 

### Reproduce link

_No response_

### Reproduce Steps

You can use a arrray to test type.

``` .ts
// rspack.config.ts
module.exports = [], // expect array shouldn't cause ts error.
```

### PR DESCRIPTION
**Pull request by suica**
## Summary

Fixes #3607.

Rspack config files should support MultiRspackOptions. But for the `Configuration` type, only "single" `RspackOptions` are used.

This PR changes the definition of `Configuration` type in `packages/rspack/src/config/types.ts` to add support to MultiRspackOptions. After this, we expect following `rspack.config.js` will emit no error:

```js
// @ts-check
/** @type {import('@rspack/cli').Configuration} */
const test = [];
module.exports = test;
```

## Test Plan

Added several test cases to ensure such configuration can pass type checking.

### CODE REVIEW

**Comment by suica** [comment]
@IWANABETHATGUY Tried to fix failed CI and passed all tests on my machine. Could you please trigger it again?

File: packages/rspack/tests/configCases/type/multiple-options/index.js [hunk 1]
```diff
@@ -0,0 +1 @@
+it("should pass type checking", function () {});
```
Comment (underfin) [inline packages/rspack/tests/configCases/type/multiple-options/index.js:1]: The type checking test is not running, you can remove it because rspack not test export type at now.

Comment (suica) [reply packages/rspack/tests/configCases/type/multiple-options/index.js:1]: Thank your for your review! This file is added deliberately as a placeholder. If it had been removed, the test would fail.
And btw, I added `test:tc` command to `package.json` to execute pure type checking for relevent config files (currently, as specified in `tsconfig.test.json`, only one file will be checked). So we are able to test the types exported by rspack now.

**Review by underfin — APPROVED** [review]

**Comment by ahabhgk** [comment]
This PR breaks [nx test suite in rspack-ecosystem-ci](https://github.com/web-infra-dev/rspack-ecosystem-ci/actions/runs/5757255254/job/15608043623)

The proper way for applying type for multi options is `/** @type {ReadonlyArray<import('webpack').RspackOptions> & import('webpack').MultiCompilerOptions} */`, and in rspack `MultiRspackOptions` is an alias for `ReadonlyArray<RspackOptions> & MultiCompilerOptions`, so you can use `/** @type {import('@rspack/cli').MultiRspackOptions} */` as a shorter

So I think we should revert this, cc @underfin
