### PR TITLE
fix: rspack errors don't support the correct location

### LINKED ISSUE #7327: [Bug]: Rspack errors seem to not support the correct location
### Details
Related to #6051

image

### Reproduce link

_No response_

### Reproduce Steps

1. Config rspack.config.js
2. Import non-existent module

### PR DESCRIPTION
**Pull request by shulaoda**
## Summary

Closed #7327 

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

File: crates/rspack_error/src/graphical.rs [hunk 1]
```diff
@@ -431,19 +431,23 @@ impl GraphicalReportHandler {
       self.theme.characters.hbar,
     )?;
 
+    let (source_line, source_col) = labels
+      .iter()
+      .find_map(|hl| {
+        lines
+          .iter()
+          .find(|line| line.span_applies(hl) && line.span_line_only(hl))
+          .map(|line| (line.line_number, self.visual_offset(line, hl.offset()) + 1))
```
Comment (h-a-n-a) [inline crates/rspack_error/src/graphical.rs:440]: In order to match the result of `Stats`, I think it would be better to use 0-based value for columns.

Comment (shulaoda) [reply crates/rspack_error/src/graphical.rs]: > In order to match the result of `Stats`, I think it would be better to use 0-based value for columns.

Is my understanding correct?

https://github.com/web-infra-dev/rspack/blob/768e43b9ed373511feacabb9dd3e34939bf8badd/crates/rspack_error/src/graphical.rs#L440-L442

Comment (h-a-n-a) [reply crates/rspack_error/src/graphical.rs]: This is great! Thank you.

**Review by h-a-n-a — APPROVED** [review]
