### PR TITLE
fix(commonjs_scanner): ignore unresolve require span

### LINKED ISSUE #3558: Bundle `jsonpath` library
### System Info

None

### Details

`https://github.com/dchester/jsonpath/issues/50`

image

Webpack is able to bundle this without resolving the two files. 

### Reproduce link

_No response_

### Reproduce Steps

None

### PR DESCRIPTION
**Pull request by suxin2017**
fixed #3558

### CODE REVIEW

File: packages/rspack/tests/statsCases/issuse-3558/module/jsonpath.js [hunk 1]
```diff
@@ -0,0 +1,6842 @@
+/*! jsonpath 1.1.1 */
```
Comment (h-a-n-a) [inline packages/rspack/tests/statsCases/issuse-3558/module/jsonpath.js:1]: Would you move this to the fixtures?

Comment (suxin2017) [reply packages/rspack/tests/statsCases/issuse-3558/module/jsonpath.js:1]: ok

File: crates/rspack_plugin_javascript/src/visitors/dependency/common_js_scanner.rs [hunk 2]
```diff
@@ -106,11 +110,17 @@ impl VisitAstPath for CommonJsScanner<'_> {
     node: &'ast CallExpr,
     ast_path: &mut AstNodePath<AstParentNodeRef<'r>>,
   ) {
-    if is_require_resolve_call(node) {
-      return self.add_require_resolve(node, ast_path, false);
-    }
-    if is_require_resolve_weak_call(node) {
-      return self.add_require_resolve(node, ast_path, true);
+    if let Callee::Expr(expr) = &node.callee {
```
Comment (h-a-n-a) [inline crates/rspack_plugin_javascript/src/visitors/dependency/common_js_scanner.rs:113]: You should change this part https://github.com/web-infra-dev/rspack/blob/59ed8c9dc637f19aedf722fef9873bcd713c5d4d/crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs#L145 too. We are migrating dependency code generation from AST to string.

Comment (h-a-n-a) [reply crates/rspack_plugin_javascript/src/visitors/dependency/common_js_scanner.rs:113]: cc @underfin

File: packages/rspack/tests/statsCases/issuse-3558/module/jsonpath.js (hunk 1 above)
Comment (ahabhgk) [reply packages/rspack/tests/statsCases/issuse-3558/module/jsonpath.js:1]: And hand write the minimal issue code instead of copy all jsonpath.js to keep the noise as low as possible

File: packages/rspack/tests/statsCases/issuse-3558/index.js [hunk 3]
```diff
@@ -0,0 +1,3 @@
+const jsonPath = require('./module/jsonpath');
+
+console.log(jsonPath);
```
Comment (h-a-n-a) [inline packages/rspack/tests/statsCases/issuse-3558/index.js:3]: Can we just leave `require("test-case-you-want")`? It looks not tidy.

**Comment by h-a-n-a** [comment]
There is a typo in the directory name `issuse-3558`, which is intended to be `issue-3358`

File: packages/rspack/tests/statsCases/issuse-3558/module/jsonpath.js (hunk 1 above)
Comment (h-a-n-a) [reply packages/rspack/tests/statsCases/issuse-3558/module/jsonpath.js:1]: > And hand write the minimal issue code instead of copy all jsonpath.js to keep the noise as low as possible

Agree

Comment (suxin2017) [reply packages/rspack/tests/statsCases/issuse-3558/module/jsonpath.js]: We shouldn't need this file, just verify that we can resolve the redefined require

File: crates/rspack_plugin_javascript/src/visitors/dependency/util.rs [hunk 4]
```diff
@@ -206,3 +206,12 @@ fn test() {
     type_args: None
   }));
 }
+
+pub fn is_unresolved_require_member_expr(expr: &Expr, unresolved_ctxt: &SyntaxContext) -> bool {
```
Comment (h-a-n-a) [inline crates/rspack_plugin_javascript/src/visitors/dependency/util.rs:210]: Would you change the name of this function since it can be used for other expressions too?

Comment (h-a-n-a) [reply crates/rspack_plugin_javascript/src/visitors/dependency/util.rs:210]: Something that is not related to `require` looks fine to me, maybe something like `is_unresolved_member_object_ident`

Comment (h-a-n-a) [reply crates/rspack_plugin_javascript/src/visitors/dependency/util.rs:210]: Would you mind me pushing some code to this PR?

**Review by h-a-n-a — APPROVED** [review]
