### PR TITLE
fix: use indirect call for TaggedTpl

### LINKED ISSUE #4380: import TaggedTemplateExpression should generate indirect call
### What problem does this feature solve?

Please get context from https://github.com/webpack/webpack/issues/17390.

### What does the proposed API of configuration look like?

-

### PR DESCRIPTION
**Pull request by bvanjoi**
Fixes #4380

The ﻿`TaggedTemplate` should be marked with ﻿`enter_call`. Consequently, it will generate an indirect call in the form of `﻿(0, xxxx)()`.

### CODE REVIEW

File: crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs [hunk 1]
```diff
@@ -4,18 +4,13 @@ use rspack_core::{
...
-      ImportSpecifier, Lit, MemberExpr, MemberProp, ModuleExportName, NamedExport, Pat, PatOrExpr,
-      Program, Prop,
-    },
-    atoms::JsWord,
-    visit::{noop_visit_type, Visit, VisitWith},
-  },
-};
+use swc_core::atoms::JsWord;
+use swc_core::common::Span;
+use swc_core::ecma::ast::{AssignExpr, AssignOp, MemberExpr, MemberProp};
```
Comment (IWANABETHATGUY) [inline crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs:9]: Maybe we could merge these ast imports?

Comment (bvanjoi) [reply crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs:9]: This is intentional. I think using the split could makes the code more readable.

Comment (IWANABETHATGUY) [reply crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs:9]: I could understand you split `atoms`, `common`, but does it make any difference split `ast` into four parts?

**Review by IWANABETHATGUY — APPROVED** [review]

**Review by ahabhgk — APPROVED** [review]
