### PR TITLE
fix: evaluate if stmt should skip import specifier in dead branch

### LINKED ISSUE #5430: Invalid syntax after evaluate if_stmt
### System Info

no need

### Details

giving:
```js
import { foo } from './c'

if (typeof require !== "undefined") {
  console.log('hello')
} else {
  console.log(foo)
}
```
result:
```js
if (true) console.log('hello');
else {}_c__WEBPACK_IMPORTED_MODULE_0__.foo
}),
```
The cause I believe is ReplaceSource, replace both the branch and imported identifier, causing one replacement appends at the end of first replacement

### Reproduce link

_No response_

### Reproduce Steps

```js
import { foo } from './c'

if (typeof require !== "undefined") {
  console.log('hello')
} else {
  console.log(foo)
}
```

### PR DESCRIPTION
**Pull request by JSerFeng**
## Summary

fix #5430 

before:
```js
it('should have correct syntax', () => {
        if (true) console.log('hello');
        else _foo__WEBPACK_IMPORTED_MODULE_0__.foo{ }
      });
```
after:
```js
it('should have correct syntax', () => {
        if (true) console.log('hello');
        else { }
      });
```

## Require Documentation?

- [ ] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

File: packages/rspack/tests/cases/parsing/evaluate-if/index.js [hunk 1]
```diff
@@ -0,0 +1,10 @@
+import { foo } from "./foo";
+
+// see issue https://github.com/web-infra-dev/rspack/issues/5430
+it("should compile", () => {
+	if (typeof require !== "undefined") {
+		console.log("hello");
```
Comment (h-a-n-a) [inline packages/rspack/tests/cases/parsing/evaluate-if/index.js:6]: Would you please avoid using `console.log` here since it flushes terminal alot?

**Review by bvanjoi — APPROVED** [review]
I think it's acceptable to land this PR, albeit it may be removed in the near future. This test case could provide useful insights.
