### PR TITLE
fix: should generate correct output when running `rspack build --json stats.json`

### LINKED ISSUE #2553: [Bug Report]: not output stats.json when `rspack build --json stats.json` called
### System Info

  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 115.13 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Safari: 15.6.1
  npmPackages:
    @rspack/cli: latest => 0.1.4 

### Details

According to the documentation, add --json will output stats.json, but actually it doesn't output.

image

image

### Reproduce link

_No response_

### Reproduce Steps

1. npm create rspack@latest
2. npm install
3. npx rspack build --json stats.json

### PR DESCRIPTION
**Pull request by hardfist**
## Summary
fixes json not write to disk when set --json and also add all js tests back 
closes #2553 
## Types of changes

- [ ] Docs change / Dependency upgrade
- [x] Bug fix
- [ ] New feature / Improvement
- [ ] Refactoring
- [ ] Breaking change

## Checklist

- [ ] I have added changeset via `pnpm run changeset`.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: packages/rspack-cli/src/commands/build.ts [hunk 1]
```diff
@@ -92,7 +93,7 @@ export class BuildCommand implements RspackCommand {
 
 				const compiler = await cli.createCompiler(
 					rspackOptions,
-					"production",
+					"buid",
```
Comment (9aoy) [inline packages/rspack-cli/src/commands/build.ts:96]: buid  => build ？

File: packages/rspack-cli/src/rspack-cli.ts [hunk 2]
```diff
@@ -18,7 +18,7 @@ import { loadRspackConfig } from "./utils/loadConfig";
 import { Mode } from "@rspack/core/src/config";
 import { RspackPluginInstance, RspackPluginFunction } from "@rspack/core";
 
-type RspackEnv = "development" | "production";
+type Command = "serve" | "buid";
```
Comment (ahabhgk) [inline packages/rspack-cli/src/rspack-cli.ts:21]: buid => build

File: packages/rspack-cli/tests/utils/test-utils.ts [hunk 3]
```diff
@@ -65,6 +65,7 @@ const createProcess = (cwd, args, options) => {
  * @returns {Promise}
  */
 const run = async (cwd, args: string[] = [], options = {}) => {
+	console.log("args:", args);
```
Comment (hyf0) [inline packages/rspack-cli/tests/utils/test-utils.ts:68]: Should remove this.

File: packages/rspack-cli/src/rspack-cli.ts (hunk 2 above)
Comment (IWANABETHATGUY) [reply packages/rspack-cli/src/rspack-cli.ts:21]: why doesn't our spell checker detect this?

Comment (IWANABETHATGUY) [reply packages/rspack-cli/src/rspack-cli.ts:21]: https://github.com/speedy-js/rspack/blob/1778fe9a9149ff328c8f649aa472ac29d91cb49a/.typos.toml#L7 it seems because of this line

**Review by 9aoy — APPROVED** [review]
