### PR TITLE
fix: resolve the inconsistent type issue in `JsModule`

### LINKED ISSUE #8937: [Bug]: TS Errors When Running With `skipLibCheck: false`
### System Info

  System:
    OS: macOS 12.7.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.82 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.18.1 - /usr/local/bin/node
    Yarn: 3.6.4 - /opt/homebrew/bin/yarn
    npm: 10.2.5 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 131.1.73.101
    Safari: 15.6.1

### Details

We're building our project which has `skipLibCheck:false` in one of our build steps.

In that process, build fails with the following TS errors:

```
webiny error: ../../node_modules/@rspack/binding/binding.d.ts(172,7): error TS2380: The return type of a 'get' accessor must be assignable to its 'set' accessor type
  Type 'undefined' is not assignable to type 'string'.
../../node_modules/@rspack/core/dist/config/index.d.ts(5,1): error TS1383: Only named exports may use 'export type'.
../../node_modules/@rspack/core/dist/exports.d.ts(36,1): error TS1383: Only named exports may use 'export type'.
```

Dug into the code a bit, and for example, for the first TS2380 error, I can see it:
Image

### Reproduce link

_No response_

### Reproduce Steps

In our repo, we've run our build process with the `skipLibCheck: false` in our TS config. With this setting, we can see the above errors.

### PR DESCRIPTION
**Pull request by shulaoda**
## Summary

closes #8937 

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Review by SoonIter — APPROVED** [review]

File: packages/rspack/src/Module.ts [hunk 1]
```diff
@@ -271,8 +271,10 @@ export class Module {
 				get(): string | undefined {
 					return module.userRequest;
 				},
-				set(val: string) {
-					module.userRequest = val;
+				set(val: string | undefined) {
+					if (val) {
```
Comment (SoonIter) [inline packages/rspack/src/Module.ts:275]: what if val is an empty string `''`?

**Review by SoonIter — DISMISSED** [review]

File: packages/rspack/src/Module.ts (hunk 1 above)
Comment (shulaoda) [reply packages/rspack/src/Module.ts:275]: The `userRequest` property exists only when the module is a `NormalModule`; it does not exist in other cases. When the `userRequest` of a `NormalModule` is an empty string (''), it might overlap in meaning with cases where the `userRequest` is absent in non-NormalModule instances. I am uncertain whether this change is appropriate.

Comment (chenjiahan) [reply packages/rspack/src/Module.ts:275]: @SyMind can you confirm this?

Comment (SyMind) [reply packages/rspack/src/Module.ts:275]: currently, Module does not have class inheritance informations on the JS side, so I think it is ok in order to solve the TS error

**Review by SyMind — APPROVED** [review]

**Comment by adrians5j** [comment]
Thanks! 😊
