### PR TITLE
fix: sources types

### LINKED ISSUE #5867: [Bug]: the type of webpack-sources is any
### System Info

Every System

### Details

image

image

### Reproduce link

_No response_

### Reproduce Steps

Every repo

### PR DESCRIPTION
**Pull request by SyMind**
## Summary

Fix #5867

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

File: packages/rspack/src/exports.ts [hunk 1]
```diff
@@ -45,7 +45,7 @@ export const WebpackError = Error;
 
 export type { Watching } from "./Watching";
 
-const sources = require("webpack-sources"); // use require to avoid wrong types, @types/webpack-sources is outdate
+import sources = require("webpack-sources");
```
Comment (chenjiahan) [inline packages/rspack/src/exports.ts:48]: Can we use `import ... from` here?

File: packages/rspack-test-tools/src/processor/hook.ts
Comment (chenjiahan) [inline packages/rspack-test-tools/src/processor/hook.ts:1]: `webpack-sources` can be moved to `devDependencies` as it is prebundled.

File: packages/rspack/src/exports.ts (hunk 1 above)
Comment (SyMind) [reply packages/rspack/src/exports.ts:48]: noop. it will enforce some problems.

The `webpack-sources.d.ts` file uses ESM to declare the module, while `webpack-sources` is implemented with CommonJS.

Using ESM import will cause misalignment between the source and the types defined.

If we declare a namespace and export default in `webpack-sources.d.ts` to fit CommonJS source, `api-extractor` will not support it.

Therefore, use `import sources = require("webpack-sources");` here.

**Review by chenjiahan — APPROVED** [review]
