### PR TITLE
fix: should create an empty codegen result for module that has failure in codegen

### LINKED ISSUE #7382: [Bug]: something was wrong ,see the picture
### Version

```sh
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 5.97 GB / 15.66 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.1202
```

### Details

image
 Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  The export "clearGlobal" in "./node_modules/@visactor/vtable/es/index.d.ts" has no internal name (existing names: )
Location: crates\rspack_core\src\concatenated_module.rs:1778

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: napi_register_module_v1
    at <unknown source file>
 2: napi_register_module_v1
    at <unknown source file>
 3: napi_register_module_v1
    at <unknown source file>
 4: napi_register_module_v1
    at <unknown source file>
 5: wasmer_vm_f64_nearest
    at <unknown source file>
 6: napi_register_module_v1
    at <unknown source file>
 7: napi_register_module_v1
    at <unknown source file>

### Reproduce link

no link

### Reproduce Steps

run build

### PR DESCRIPTION
**Pull request by JSerFeng**
## Summary

fix #7382

When `code_generation` returns an `Err`, we should push this error to diagnostics and keep a empty `CodegenerateResult` like webpack
Parse error in concatenatedModule should be added to compilation diagnostics.

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

File: crates/rspack_core/src/compiler/compilation.rs [hunk 1]
```diff
@@ -869,19 +869,33 @@ impl Compilation {
...
-          .old_cache
-          .code_generate_occasion
-          .use_cache(job, |module, runtime| {
-            let module = module_graph
-              .module_by_identifier(&module)
-              .expect("should have module");
-            module.code_generation(self, Some(runtime), None)
-          })
-          .map(|(res, runtimes, from_cache)| (module, res, runtimes, from_cache))
+        let runtimes = job.runtimes.clone();
```
Comment (ahabhgk) [inline crates/rspack_core/src/compiler/compilation.rs:872]: Can we avoid the clone here if we `map` the result of `use_cache`

File: crates/rspack_core/src/concatenated_module.rs [hunk 2]
```diff
@@ -1715,21 +1715,22 @@ impl ConcatenatedModule {
...
-          return Ok(ModuleInfo::Concatenated(module_info));
+
+          // return empty error as we already push error to compilation.diagnostics
+          return Err(
+            rspack_error::TraceableError::from_source_file(
+              &fm,
+              span.start as usize,
+              span.end as usize,
+              format!(
+                "{} parsing error:\n",
```
Comment (h-a-n-a) [inline crates/rspack_core/src/concatenated_module.rs:1726]: This looks a bit weird. It should be `"JavaScript parsing error:"` here and use `Diagnostic::with_module_identifier` to link it with the module.

Comment (JSerFeng) [reply crates/rspack_core/src/concatenated_module.rs:1726]: Got it

File: crates/rspack_core/src/compiler/compilation.rs (hunk 1 above)
Comment (JSerFeng) [reply crates/rspack_core/src/compiler/compilation.rs:873]: it needs clone anyway in the next step

**Review by ahabhgk — APPROVED** [review]
