### PR TITLE
fix: minimize don't support output target equal "module"

### LINKED ISSUE #3615: When exporting esm products, the build fails.
### System Info

System:
    - OS: macOS 13.4
    - CPU: (12) arm64 Apple M2 Pro
    - Memory: 1.67 GB / 32.00 GB
    - Shell: 5.9 - /bin/zsh
  Binaries:
    - Node: 16.19.1 - ~/Library/Caches/fnm_multishells/17210_1687673479626/bin/node
    - Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/17210_1687673479626/bin/yarn
    - npm: 8.19.3 - ~/Library/Caches/fnm_multishells/17210_1687673479626/bin/npm
  Browsers:
    - Chrome: 114.0.5735.133
    - Safari: 16.5
  npmPackages:
    - @rspack/cli: ^0.2.3 => 0.2.3

### Details

rspack.config.js
``` js
/**
 * @type {import('@rspack/cli').Configuration}
 */
const esmConfig = {
	context: __dirname,
	entry: {
		main: "./src/index.ts"
	},
	// optimization: {
	// 	minimize: false,
	// },
	output: {
		path: './dist/esm',
		module: true,
		libraryTarget: 'module'
	},
	experiments: {
	        outputModule: true,
	},
};

module.exports = [esmConfig];
```

./src/index.ts
``` ts
export default function () {
  console.info('hell world');
}

export const add = (a, b) => {
  return a + b;
}
```

Run build command:
image

When add `optimization.minimize = false`, the build task work.

rspack.config.js
``` js
/**
 * @type {import('@rspack/cli').Configuration}
 */
const esmConfig = {
	context: __dirname,
	entry: {
		main: "./src/index.ts"
	},
	optimization: {
	    minimize: false,
	},
	output: {
		path: './dist/esm',
		module: true,
		libraryTarget: 'module'
	},
	experiments: {
	        outputModule: true,
	},
};

module.exports = [esmConfig];
```

Webpack works fine with the same configuration as above.

### Reproduce link

_No response_

### Reproduce Steps

None.

### PR DESCRIPTION
**Pull request by suxin2017**
close #3615 

## Summary

Modify the minimize option to support the module type

[swc playground](https://play.swc.rs/?version=1.3.66&code=H4sIAAAAAAAAA4VUwY6bMBC98xVTelhQUVZtb0HppeqhUletVu0pWlkGhg27YFNjJ1ut8u8dYxuSLdkipESeefPejN%2Bw5woYO2DR8%2FKRdbIyLQ6MwQaeo%2FjD%2B4%2FxGmojSt1IAYkLZ4BPvVR6yE6QCn%2BbRiFjqQWaAWHQqil1nEffiwcs9arCuhH4Q8kelf6TTDVixnC4GSvHGYGBnj1vDa5BK4PRMc2jSQJzsERzdY86A962qcfUUiV76kbwDqERY2iZOoBtZmC0DwrToeJF66mzKULpa1twayF347GVdYyCnqkbV40IuWn1PLskPeFRqI2iXnxW7uo5Nl5Vr6MowQNeTMZXmzClFINscdWIWiZXO2xbOEjVVlejcBvVthjddMIzKNLNJ4cLPPAOCsqkN4sIcH0NP3cIzgJQ8nKHEewX3MPGmLPQ8VTgv17xhvpaWc1E8HmH5SM0dWBpBnuRnss%2FlnI8qZxniOaSgm0of5dPcCqenMHfbDZghHNINc%2FbT%2BE0deUvORQ7%2Bl8rXCHXSDMTeAjiEy4q6I2Ghl6hJeidn1saza10oYnk%2F12MSxm86rSsacZBTprPgr48YWlIkZ6vLFyET1pY%2Bplp2vTurPPlhc%2Ft1d26eVk%2BnwyyPqGPwkS7F7Mka527yEdGAy15ZvwqpfkFkHP0QmAbUygmJ1wA%2BvW5BPZhW8CdwvMlej7YvcpeI6GU8JdWhOb3FgZpVIk3vO8bcf%2Fr9tum441YdQ%2FDquP9X56pNimmBQAA&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rrbdtE79BCIOhEVP9mOVBTl7gUCbbPD854Z2Cal4MUG7morxzIkTYz0nQvhHES%2FCwHJCdmQTQKXkQrXaNaOsaH9SEA0LSh1C%2Fna6%2BBiZBz1zrwNds7%2FQhN9ImQ%2BF2tVh8XhWTd1Jfj4XFvYP1Ife%2Bhv8CsNmdDa7gXLj7FY2bR%2FAL1vegMTAQAA)

Modify minimize to support the module type

### CODE REVIEW

**Review by jerrykingxyz — APPROVED** [review]

File: packages/rspack/tests/configCases/library/esmodule/index.js [hunk 1]
```diff
@@ -0,0 +1,8 @@
+export default function () {
+	console.info("hell world");
```
Comment (zackarychapple) [inline packages/rspack/tests/configCases/library/esmodule/index.js:2]: nit pick but should be `hello world` not `hell world`

File: crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs [hunk 2]
```diff
@@ -225,6 +225,12 @@ impl Plugin for JsPlugin {
   ) -> PluginProcessAssetsOutput {
     let compilation = args.compilation;
     let minify_options = &compilation.options.builtins.minify_options;
+    let is_module = compilation
+      .options
+      .output
+      .library
+      .as_ref()
+      .is_some_and(|library| library.library_type == "module");
```
Comment (f0reclone) [inline crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs:233]: @zackarychapple @suxin2017 I just stumbled upon this MR because I have a similar issue with output.library.type = 'system'.  In 2 of 3 cases it fails due to the error: ^^^^^^ 'import', and 'export' cannot be used outside of module code. Should we add systemjs as another type here?
