### PR TITLE
fix: initial watching should stale until invalidate happens

### LINKED ISSUE #2585: [Bug Report]: create more than some count multiple compiler rspack break
### System Info

System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC
    Memory: 628.22 MB / 1.63 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 20220528.183901.0 - /usr/local/bin/watchman
  npmPackages:
    @rspack/cli: ^0.1.1 => 0.1.1 
    @rspack/core: ^0.1.5 => 0.1.5 
    @rspack/dev-server: ^0.1.5 => 0.1.5

### Details

local hava many package, when i create more than some count multiple compiler, rspack break

```
[Error: error[internal]: Failed to resolve render_manifest results: JoinError::Panic(Id(123), ...).
Raw: panicked at 'Failed to resolve render_manifest results: JoinError::Panic(Id(123), ...)', /build/crates/rspack_core/src/compiler/compilation.rs:926:8
This is not expected, please file an issue at https://github.com/web-infra-dev/rspack/issues.

   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: start_thread
  27: clone

] {
  code: 'GenericFailure'
}
undefined
```

### Reproduce link

https://codesandbox.io/p/sandbox/snowy-cdn-cgr6t5?file=%2Fbuild.js&selection=%5B%7B%22endColumn%22%3A25%2C%22endLineNumber%22%3A26%2C%22startColumn%22%3A9%2C%22startLineNumber%22%3A26%7D%5D

### Reproduce Steps

1. `pnpm i`
2. `node build.js`

### PR DESCRIPTION
**Pull request by JSerFeng**
## Summary

Watching should be still #initial until invalidate happens, as multiCompiler may block the watching first run

## Related issue (if exists)

closes #2585 

## Types of changes

- [ ] Docs change / Dependency upgrade
- [x] Bug fix
- [ ] New feature / Improvement
- [ ] Refactoring
- [ ] Breaking change

## Checklist

- [x] I have added changeset via `pnpm run changeset`.
- [x] I have added tests to cover my changes.

### CODE REVIEW

File: packages/rspack/src/watching.ts [hunk 1]
```diff
@@ -258,14 +259,16 @@ class Watching {
...
+	private _done(error: Error, compilation: null): void;
+	private _done(error: null, compilation: Compilation): void;
+	private _done(error: Error | null, compilation: Compilation | null) {
 		this.running = false;
 		const handleError = (err?: Error, cbs?: Callback<Error, void>[]) => {
 			// @ts-expect-error
 			this.compiler.hooks.failed.call(err);
 			// this.compiler.cache.beginIdle();
 			// this.compiler.idle = true;
-			this.handler(err, stats);
```
Comment (ahabhgk) [inline packages/rspack/src/watching.ts:268]: Why remove this?

**Review by ahabhgk — CHANGES_REQUESTED** [review]

**Comment by ahabhgk** [comment]
Would be better to add some test cases

File: packages/rspack/src/watching.ts (hunk 1 above)
Comment (JSerFeng) [reply packages/rspack/src/watching.ts]: Modified

Comment (JSerFeng) [reply packages/rspack/src/watching.ts]: > Would be better if you can add some test cases

Done

**Review by ahabhgk — APPROVED** [review]
