### PR TITLE
fix: computed member expression on exports

### LINKED ISSUE #5638: [Bug]: exports is not defined
### System Info

  System:
    OS: macOS 13.6.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 460.93 MB / 32.00 GB
    Shell: 3.7.0 - /usr/local/bin/fish
  Binaries:
    Node: 18.12.0 - /usr/bin/node
    Yarn: 1.22.15 - /usr/bin/yarn
    npm: 9.2.0 - /home/linuxbrew/.linuxbrew/bin/npm
  npmPackages:
    @rspack/cli: ^0.5.4 => 0.5.4 
    @rspack/core: ^0.5.4 => 0.5.4 
    @rspack/plugin-react-refresh: ^0.5.4 => 0.5.4 

### Details

I'm getting the following error

```
Uncaught ReferenceError: exports is not defined
```

Which points to this piece of code

```js
    "../node_modules/@babel/polyfill/node_modules/core-js/modules/_typed-buffer.js": (function(__unused_webpack_module, __unused_webpack_exports, __webpack_require__) {
        'use strict';
        var global = __webpack_require__(/*! ./_global */
        "../node_modules/@babel/polyfill/node_modules/core-js/modules/_global.js");
        var DESCRIPTORS = __webpack_require__(/*! ./_descriptors */
        "../node_modules/@babel/polyfill/node_modules/core-js/modules/_descriptors.js");
        var LIBRARY = __webpack_require__(/*! ./_library */
        "../node_modules/@babel/polyfill/node_modules/core-js/modules/_library.js");
        var $typed = __webpack_require__(/*! ./_typed */
        "../node_modules/@babel/polyfill/node_modules/core-js/modules/_typed.js");
        var hide = __webpack_require__(/*! ./_hide */
        "../node_modules/@babel/polyfill/node_modules/core-js/modules/_hide.js");
        var redefineAll = __webpack_require__(/*! ./_redefine-all */
        "../node_modules/@babel/polyfill/node_modules/core-js/modules/_redefine-all.js");
        var fails = __webpack_require__(/*! ./_fails */
        "../node_modules/@babel/polyfill/node_modules/core-js/modules/_fails.js");
        var anInstance = __webpack_require__(/*! ./_an-instance */
        "../node_modules/@babel/polyfill/node_modules/core-js/modules/_an-instance.js");
        var toInteger = __webpack_require__(/*! ./_to-integer */
        "../node_modules/@babel/polyfill/node_modules/core-js/modules/_to-integer.js");
        var toLength = __webpack_require__(/*! ./_to-length */
        "../node_modules/@babel/polyfill/node_modules/core-js/modules/_to-length.js");
        var toIndex = __webpack_require__(/*! ./_to-index */
        "../node_modules/@babel/polyfill/node_modules/core-js/modules/_to-index.js");
        var gOPN = __webpack_require__(/*! ./_object-gopn */
        "../node_modules/@babel/polyfill/node_modules/core-js/modules/_object-gopn.js")/* .f */
        .f;
        var dP = __webpack_require__(/*! ./_object-dp */
        "../node_modules/@babel/polyfill/node_modules/core-js/modules/_object-dp.js")/* .f */
        .f;
        var arrayFill = __webpack_require__(/*! ./_array-fill */
        "../node_modules/@babel/polyfill/node_modules/core-js/modules/_array-fill.js");
        var setToStringTag = __webpack_require__(/*! ./_set-to-string-tag */
        "../node_modules/@babel/polyfill/node_modules/core-js/modules/_set-to-string-tag.js");
        var ARRAY_BUFFER = 'ArrayBuffer';
        var DATA_VIEW = 'DataView';
        var PROTOTYPE = 'prototype';
        var WRONG_LENGTH = 'Wrong length!';
        var WRONG_INDEX = 'Wrong index!';
        var $ArrayBuffer = global[ARRAY_BUFFER];
        var $DataView = global[DATA_VIEW];
        var Math = global.Math;
        var RangeError = global.RangeError;
        // eslint-disable-next-line no-shadow-restricted-names
        var Infinity1 = global.Infinity;
        var BaseBuffer = $ArrayBuffer;
        var abs = Math.abs;
        var pow = Math.pow;
        var floor = Math.floor;
        var log = Math.log;
        var LN2 = Math.LN2;
        var BUFFER = 'buffer';
        var BYTE_LENGTH = 'byteLength';
        var BYTE_OFFSET = 'byteOffset';
        var $BUFFER = DESCRIPTORS ? '_b' : BUFFER;
        var $LENGTH = DESCRIPTORS ? '_l' : BYTE_LENGTH;
        var $OFFSET = DESCRIPTORS ? '_o' : BYTE_OFFSET;
        // IEEE754 conversions based on https://github.com/feross/ieee754
        function packIEEE754(value, mLen, nBytes) {
            var buffer = new Array(nBytes);
            var eLen = nBytes * 8 - mLen - 1;
            var eMax = (1 << eLen) - 1;
            var eBias = eMax >> 1;
            var rt = mLen === 23 ? pow(2, -24) - pow(2, -77) : 0;
            var i = 0;
            var s = value < 0 || value === 0 && 1 / value < 0 ? 1 : 0;
            var e, m, c;
            value = abs(value);
            // eslint-disable-next-line no-self-compare
            if (value != value || value === Infinity) {
                // eslint-disable-next-line no-self-compare
                m = value != value ? 1 : 0;
                e = eMax;
            } else {
                e = floor(log(value) / LN2);
                if (value * (c = pow(2, -e)) < 1) {
                    e--;
                    c *= 2;
                }
                if (e + eBias >= 1)
                    value += rt / c;
                else
                    value += rt * pow(2, 1 - eBias);
                if (value * c >= 2) {
                    e++;
                    c /= 2;
                }
                if (e + eBias >= eMax) {
                    m = 0;
                    e = eMax;
                } else if (e + eBias >= 1) {
                    m = (value * c - 1) * pow(2, mLen);
                    e = e + eBias;
                } else {
                    m = value * pow(2, eBias - 1) * pow(2, mLen);
                    e = 0;
                }
            }
            for (; mLen >= 8; buffer[i++] = m & 255,
            m /= 256,
            mLen -= 8)
                ;
            e = e << mLen | m;
            eLen += mLen;
            for (; eLen > 0; buffer[i++] = e & 255,
            e /= 256,
            eLen -= 8)
                ;
            buffer[--i] |= s * 128;
            return buffer;
        }
        function unpackIEEE754(buffer, mLen, nBytes) {
            var eLen = nBytes * 8 - mLen - 1;
            var eMax = (1 << eLen) - 1;
            var eBias = eMax >> 1;
            var nBits = eLen - 7;
            var i = nBytes - 1;
            var s = buffer[i--];
            var e = s & 127;
            var m;
            s >>= 7;
            for (; nBits > 0; e = e * 256 + buffer[i],
            i--,
            nBits -= 8)
                ;
            m = e & (1 << -nBits) - 1;
            e >>= -nBits;
            nBits += mLen;
            for (; nBits > 0; m = m * 256 + buffer[i],
            i--,
            nBits -= 8)
                ;
            if (e === 0)
                e = 1 - eBias;
            else if (e === eMax)
                return m ? NaN : s ? -Infinity : Infinity;
            else {
                m = m + pow(2, mLen);
                e = e - eBias;
            }
            return (s ? -1 : 1) * m * pow(2, e - mLen);
        }
        function unpackI32(bytes) {
            return bytes[3] << 24 | bytes[2] << 16 | bytes[1] << 8 | bytes[0];
        }
        function packI8(it) {
            return [it & 0xff];
        }
        function packI16(it) {
            return [it & 0xff, it >> 8 & 0xff];
        }
        function packI32(it) {
            return [it & 0xff, it >> 8 & 0xff, it >> 16 & 0xff, it >> 24 & 0xff];
        }
        function packF64(it) {
            return packIEEE754(it, 52, 8);
        }
        function packF32(it) {
            return packIEEE754(it, 23, 4);
        }
        function addGetter(C, key, internal) {
            dP(C[PROTOTYPE], key, {
                get: function() {
                    return this[internal];
                }
            });
        }
        function get(view, bytes, index, isLittleEndian) {
            var numIndex = +index;
            var intIndex = toIndex(numIndex);
            if (intIndex + bytes > view[$LENGTH])
                throw RangeError(WRONG_INDEX);
            var store = view[$BUFFER]._b;
            var start = intIndex + view[$OFFSET];
            var pack = store.slice(start, start + bytes);
            return isLittleEndian ? pack : pack.reverse();
        }
        function set(view, bytes, index, conversion, value, isLittleEndian) {
            var numIndex = +index;
            var intIndex = toIndex(numIndex);
            if (intIndex + bytes > view[$LENGTH])
                throw RangeError(WRONG_INDEX);
            var store = view[$BUFFER]._b;
            var start = intIndex + view[$OFFSET];
            var pack = conversion(+value);
            for (var i = 0; i < bytes; i++)
                store[start + i] = pack[isLittleEndian ? i : bytes - i - 1];
        }
        if (!$typed.ABV) {
            $ArrayBuffer = function ArrayBuffer(length) {
                anInstance(this, $ArrayBuffer, ARRAY_BUFFER);
                var byteLength = toIndex(length);
                this._b = arrayFill.call(new Array(byteLength), 0);
                this[$LENGTH] = byteLength;
            }
            ;
            $DataView = function DataView(buffer, byteOffset, byteLength) {
                anInstance(this, $DataView, DATA_VIEW);
                anInstance(buffer, $ArrayBuffer, DATA_VIEW);
                var bufferLength = buffer[$LENGTH];
                var offset = toInteger(byteOffset);
                if (offset < 0 || offset > bufferLength)
                    throw RangeError('Wrong offset!');
                byteLength = byteLength === undefined ? bufferLength - offset : toLength(byteLength);
                if (offset + byteLength > bufferLength)
                    throw RangeError(WRONG_LENGTH);
                this[$BUFFER] = buffer;
                this[$OFFSET] = offset;
                this[$LENGTH] = byteLength;
            }
            ;
            if (DESCRIPTORS) {
                addGetter($ArrayBuffer, BYTE_LENGTH, '_l');
                addGetter($DataView, BUFFER, '_b');
                addGetter($DataView, BYTE_LENGTH, '_l');
                addGetter($DataView, BYTE_OFFSET, '_o');
            }
            redefineAll($DataView[PROTOTYPE], {
                getInt8: function getInt8(byteOffset) {
                    return get(this, 1, byteOffset)[0] << 24 >> 24;
                },
                getUint8: function getUint8(byteOffset) {
                    return get(this, 1, byteOffset)[0];
                },
                getInt16: function getInt16(byteOffset /* , littleEndian */
                ) {
                    var bytes = get(this, 2, byteOffset, arguments[1]);
                    return (bytes[1] << 8 | bytes[0]) << 16 >> 16;
                },
                getUint16: function getUint16(byteOffset /* , littleEndian */
                ) {
                    var bytes = get(this, 2, byteOffset, arguments[1]);
                    return bytes[1] << 8 | bytes[0];
                },
                getInt32: function getInt32(byteOffset /* , littleEndian */
                ) {
                    return unpackI32(get(this, 4, byteOffset, arguments[1]));
                },
                getUint32: function getUint32(byteOffset /* , littleEndian */
                ) {
                    return unpackI32(get(this, 4, byteOffset, arguments[1])) >>> 0;
                },
                getFloat32: function getFloat32(byteOffset /* , littleEndian */
                ) {
                    return unpackIEEE754(get(this, 4, byteOffset, arguments[1]), 23, 4);
                },
                getFloat64: function getFloat64(byteOffset /* , littleEndian */
                ) {
                    return unpackIEEE754(get(this, 8, byteOffset, arguments[1]), 52, 8);
                },
                setInt8: function setInt8(byteOffset, value) {
                    set(this, 1, byteOffset, packI8, value);
                },
                setUint8: function setUint8(byteOffset, value) {
                    set(this, 1, byteOffset, packI8, value);
                },
                setInt16: function setInt16(byteOffset, value /* , littleEndian */
                ) {
                    set(this, 2, byteOffset, packI16, value, arguments[2]);
                },
                setUint16: function setUint16(byteOffset, value /* , littleEndian */
                ) {
                    set(this, 2, byteOffset, packI16, value, arguments[2]);
                },
                setInt32: function setInt32(byteOffset, value /* , littleEndian */
                ) {
                    set(this, 4, byteOffset, packI32, value, arguments[2]);
                },
                setUint32: function setUint32(byteOffset, value /* , littleEndian */
                ) {
                    set(this, 4, byteOffset, packI32, value, arguments[2]);
                },
                setFloat32: function setFloat32(byteOffset, value /* , littleEndian */
                ) {
                    set(this, 4, byteOffset, packF32, value, arguments[2]);
                },
                setFloat64: function setFloat64(byteOffset, value /* , littleEndian */
                ) {
                    set(this, 8, byteOffset, packF64, value, arguments[2]);
                }
            });
        } else {
            if (!fails(function() {
                $ArrayBuffer(1);
            }) || !fails(function() {
                new $ArrayBuffer(-1);
                // eslint-disable-line no-new
            }) || fails(function() {
                new $ArrayBuffer();
                // eslint-disable-line no-new
                new $ArrayBuffer(1.5);
                // eslint-disable-line no-new
                new $ArrayBuffer(NaN);
                // eslint-disable-line no-new
                return $ArrayBuffer.name != ARRAY_BUFFER;
            })) {
                $ArrayBuffer = function ArrayBuffer(length) {
                    anInstance(this, $ArrayBuffer);
                    return new BaseBuffer(toIndex(length));
                }
                ;
                var ArrayBufferProto = $ArrayBuffer[PROTOTYPE] = BaseBuffer[PROTOTYPE];
                for (var keys = gOPN(BaseBuffer), j = 0, key; keys.length > j; )
                    if (!((key = keys[j++])in $ArrayBuffer))
                        hide($ArrayBuffer, key, BaseBuffer[key]);
                if (!LIBRARY)
                    ArrayBufferProto.constructor = $ArrayBuffer;
            }
            // iOS Safari 7.x bug
            var view = new $DataView(new $ArrayBuffer(2));
            var $setInt8 = $DataView[PROTOTYPE].setInt8;
            view.setInt8(0, 2147483648);
            view.setInt8(1, 2147483649);
            if (view.getInt8(0) || !view.getInt8(1))
                redefineAll($DataView[PROTOTYPE], {
                    setInt8: function setInt8(byteOffset, value) {
                        $setInt8.call(this, byteOffset, value << 24 >> 24);
                    },
                    setUint8: function setUint8(byteOffset, value) {
                        $setInt8.call(this, byteOffset, value << 24 >> 24);
                    }
                }, true);
        }
        setToStringTag($ArrayBuffer, ARRAY_BUFFER);
        setToStringTag($DataView, DATA_VIEW);
        hide($DataView[PROTOTYPE], $typed.VIEW, true);
        exports[ARRAY_BUFFER] = $ArrayBuffer;
        exports[DATA_VIEW] = $DataView;
    }
    ),
```

It seems like the function argument is called `__unused_webpack_exports` while `exports` is used in the body. When using webpac, both are equal to `exports`

### Reproduce link

_No response_

### Reproduce Steps

I'm not sure yet how to create a small reproduction. Let me know if necessary and I'll try

### PR DESCRIPTION
**Pull request by LingyuCoder**
## Summary

Fix #5638

## Require Documentation?

- [x] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

File: crates/rspack_core/src/utils/visitor.rs [hunk 1]
```diff
@@ -62,9 +62,21 @@ impl ExpressionInfoCallExpression {
...
+impl ExpressionInfoMemberExpression {
+  pub fn obj(&self) -> &MemberExpr {
+    &self.object
+  }
+}
+
 #[derive(Debug)]
 pub enum ExpressionInfoKind {
   CallExpression(Box<ExpressionInfoCallExpression>),
+  MemberExpression(Box<ExpressionInfoMemberExpression>),
```
Comment (bvanjoi) [inline crates/rspack_core/src/utils/visitor.rs:79]: I don't think this is the optimal solution. We performed many similar tasks during the ﻿`walk_member`, and our ultimate goal is to align with webpack.

Comment (LingyuCoder) [reply crates/rspack_core/src/utils/visitor.rs:79]: This is aligning with webpack. Webpack walk member expression and if exports[xxx].aaa, it will return object with member expression, then the return value of getMemberExpressionInfo  will be undefined, and the assignMembers hook will not be triggered.

```js
extractMemberExpressionChain(expression) {
	/** @type {AnyNode} */
	let expr = expression;
	const members = [];
	const membersOptionals = [];
	const memberRanges = [];
	// exports[xxx]
	while (expr.type === "MemberExpression") {
		if (expr.computed) { // is computed
			if (expr.property.type !== "Literal") break; // is not literal, break and object = expr
			members.push(`${expr.property.value}`); // the literal
			memberRanges.push(expr.object.range); // the range of the expression fragment before the literal
		}
                // ...
	}

	return {
		members,
		membersOptionals,
		memberRanges,
		object: expr // object = exports[xxx] and it is a member expression
	};
}

getMemberExpressionInfo(expression, allowedTypes) {
	const { object, members, membersOptionals, memberRanges } =
		this.extractMemberExpressionChain(expression);
	// object = exports[xxx], object.type === MemberExpression
	// return undefined
	switch (object.type) {
		case "CallExpression": {
			// ...
		}
		case "Identifier":
		case "MetaProperty":
		case "ThisExpression": {
			// ...
		}
	}
}
```

Comment (bvanjoi) [reply crates/rspack_core/src/utils/visitor.rs:79]: No, what I mean is we've already done the same thing in [javascript_parser::MemberExpressionInfo](https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs#L56-L60). Therefore, this change seems unnecessary.

Furthermore, I think that ﻿`utils::extract_member_expression_chain` can ultimately be removed.

Comment (LingyuCoder) [reply crates/rspack_core/src/utils/visitor.rs:79]: Here needs to distinguish between `exports[xxx]` and `exports`, currently the `utils::extract_member_expression_chain` will return an empty array in both cases, and then make the logic of handling `exports` ran on `exports[xxx]`. Is there any other recommended way?

Comment (LingyuCoder) [reply crates/rspack_core/src/utils/visitor.rs:79]: > Furthermore, I think that ﻿`utils::extract_member_expression_chain` can ultimately be removed.

I agree

Comment (bvanjoi) [reply crates/rspack_core/src/utils/visitor.rs:79]: > Is there any other recommended way?

If I understand correctly, I believe we need to port over this logic: https://github.com/webpack/webpack/blob/main/lib/dependencies/CommonJsExportsParserPlugin.js#L308-L349.

Comment (LingyuCoder) [reply crates/rspack_core/src/utils/visitor.rs:79]: > Perhaps I can use parser.get_member_expression_info to handle this?

No method to get members on parser::MemberExpressionInfo. T_T

Comment (bvanjoi) [reply crates/rspack_core/src/utils/visitor.rs:79]: > Perhaps I can use parser.get_member_expression_info to handle this?

If it functions as anticipated, I think we can consider this as a temporary solution.

**Review by bvanjoi — APPROVED** [review]
