### PR TITLE
fix: bump swc to fix many bugs

### LINKED ISSUE #3019: _typeof is not defined
### System Info

@rspack/cli 0.1.9

### Details

runtime with error `_typeof is not defined`

### Reproduce link

_No response_

### Reproduce Steps

```js
// src/index.js
function _typeof(obj) {
  "@babel/helpers - typeof";

  return (
    (_typeof =
      "function" == typeof Symbol && "symbol" == typeof Symbol.iterator
        ? function (obj) {
            return typeof obj;
          }
        : function (obj) {
            return obj &&
              "function" == typeof Symbol &&
              obj.constructor === Symbol &&
              obj !== Symbol.prototype
              ? "symbol"
              : typeof obj;
          }),
    _typeof(obj)
  );
}
function a(op, paramA, paramB) {
  if ("=" === op) return paramA === paramB;
  if (-1 !== ["=", "<", ">", ">=", "<=", "!="].indexOf(op))
    return eval("" + paramA + op + paramB);
  if (-1 !== ["in", "contains"].indexOf(op))
    return -1 !== paramB.indexOf(paramA);
  if (-1 !== ["is not null", "is null"].indexOf(op))
    return "is null" === op ? null == paramA : null != paramA;
  if (-1 !== ["startswith", "endswith"].indexOf(op)) {
    if ("startswith" === op) return 0 === paramA.indexOf(paramB);
    var start = paramA.length - paramB.length,
      str = paramA.substr(start, paramB.length);
    return str === paramB;
  }
}

var freeGlobal = _typeof({});
```
``` js
// rspack.config.js
module.exports = {
  stats: { preset: "normal" },
  target: ["web", "es5"],
  builtins: {
    html: [
      {
        filename: "index.html",
      },
    ],
  },
  entry: {
    "main": "./src/index.js",
  },
}
```

### PR DESCRIPTION
**Pull request by hyf0**
## Related issue (if exists)

Fixes #3019.

### <samp>🤖 Generated by Copilot at f5f84f9</samp>

Updated swc dependencies and added support for TypeScript `using` declarations in the tree shaking visitors. Refactored a JSX component to a regular function.

<details open=true>
  <summary><h2>Walkthrough</h2></summary>

### <samp>🤖 Generated by Copilot at f5f84f9</samp>

*  Update swc dependencies to the latest versions in `Cargo.toml` ([link](https://github.com/web-infra-dev/rspack/pull/3279/files?diff=unified&w=0#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L57-R65))
*  Add placeholders for handling the new `Decl::Using` variant from swc in the tree shaking visitors for the core and JavaScript plugins ([link](https://github.com/web-infra-dev/rspack/pull/3279/files?diff=unified&w=0#diff-9256f31ef29461b1e1f2648e534a8c337b8144a30679154ada803910c6039440R638-R641), [link](https://github.com/web-infra-dev/rspack/pull/3279/files?diff=unified&w=0#diff-9256f31ef29461b1e1f2648e534a8c337b8144a30679154ada803910c6039440L1070-R1074), [link](https://github.com/web-infra-dev/rspack/pull/3279/files?diff=unified&w=0#diff-9256f31ef29461b1e1f2648e534a8c337b8144a30679154ada803910c6039440R1588), [link](https://github.com/web-infra-dev/rspack/pull/3279/files?diff=unified&w=0#diff-c5218dcdb499019aee70f975e9ae8b7b965922bc593ddb2beca6bd55dc9eb430R246-R249))
*  Refactor `App` component from an arrow function to a regular function in the test case for the module type rule set ([link](https://github.com/web-infra-dev/rspack/pull/3279/files?diff=unified&w=0#diff-c5bc5e84328237a74266e1c651dd9186bf4f587316d536381408849e08487fcdL7-R10))

</details>

### CODE REVIEW

File: crates/rspack_plugin_javascript/src/visitors/tree_shaking.rs [hunk 1]
```diff
@@ -243,6 +243,10 @@ impl<'a> TreeShaker<'a> {
           }))
         }
       }
+      Decl::Using(_) => {
+        // TODO(hyf0): swc bump
+        unimplemented!()
```
Comment (hyf0) [inline crates/rspack_plugin_javascript/src/visitors/tree_shaking.rs:248]: @IWANABETHATGUY I'll create an issue for this.

File: packages/rspack/tests/configCases/rule-set/module-type/app.tsx [hunk 2]
```diff
@@ -4,4 +4,7 @@ const React = {
 function Component<T>() {
 	return <div></div>;
 }
-export const App = () => <Component<any>></Component>;
```
Comment (hyf0) [inline packages/rspack/tests/configCases/rule-set/module-type/app.tsx:7]: See details at https://github.com/swc-project/swc/issues/7444

**Review by IWANABETHATGUY — APPROVED** [review]
