### PR TITLE
fix(css/modules): bump swc version to fix #3875 and add test

### LINKED ISSUE #3875: [css modules] class is disappear when compose is chained
### System Info

System:
OS: macOS 13.4
CPU: (8) arm64 Apple M2
Memory: 41.41 MB / 24.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 16.20.1 - ~/.nodebrew/current/bin/node
Yarn: 3.6.1 - ~/.nodebrew/current/bin/yarn
npm: 8.19.4 - ~/.nodebrew/current/bin/npm
pnpm: 8.6.6 - ~/.nodebrew/current/bin/pnpm
Browsers:
Chrome: 114.0.5735.198
Safari: 16.5

### Details

When build the following css, js output is broken.
```css
.child-class2 {
  color: red;
}

.child-class {
  composes: child-class2;
}

.root-class {
  composes: child-class;
}
```

output js:
```js
module.exports = {
  "child-class": "_080c451ce1b195f77441" + " " + "a00ce76145ebf46808fa",
  "child-class2": "a00ce76145ebf46808fa",
  "root-class": "bf6ebeeee1f6790ffdff" + " " + "_080c451ce1b195f77441",
};
```

expected output:
```diff
module.exports = {
  "child-class": "_080c451ce1b195f77441" + " " + "a00ce76145ebf46808fa",
  "child-class2": "a00ce76145ebf46808fa",
- "root-class": "bf6ebeeee1f6790ffdff" + " " + "_080c451ce1b195f77441",
+ "root-class": "bf6ebeeee1f6790ffdff" + " " + "_080c451ce1b195f77441" + " " + "a00ce76145ebf46808fa",
};
```

### Reproduce link

https://github.com/Thiry1/rspack-bug-repro/tree/04fbcbc39a2005a9f178cefecec6f9b0b7bae42e

### Reproduce Steps

1. run npm run build
2. see ./rspack-dist/main.js (you can see webpack's output on ./webpack-dist/main.js)

### PR DESCRIPTION
**Pull request by Thiry1**
## Summary
bump swc version to fix #3875 and add test.
closes #3875

see also:
https://github.com/swc-project/swc/pull/7917

## Test Plan
unit test

## Require Documentation?

- [x] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

File: crates/rspack_plugin_javascript/src/ast/stringify.rs [hunk 1]
```diff
@@ -77,12 +77,10 @@ pub fn print(
       }
 
       let mut emitter = Emitter {
-        cfg: codegen::Config {
-          minify,
-          target,
-          ascii_only,
-          ..Default::default()
-        },
+        cfg: codegen::Config::default()
```
Comment (Thiry1) [inline crates/rspack_plugin_javascript/src/ast/stringify.rs:80]: This change is caused by https://github.com/swc-project/swc/commit/ee7575695de6dad140457ffb8bb8f0ac80c4dcdc#diff-7c02e040b4abd4d6a4c5c79c50c6976d065e7da0fe25a33f02b0da74a838cddb

File: crates/rspack_plugin_css/tests/fixtures/custom/composes/snapshot/output.snap [hunk 2]
```diff
@@ -0,0 +1,28 @@
+---
```
Comment (Thiry1) [inline crates/rspack_plugin_css/tests/fixtures/custom/composes/snapshot/output.snap:1]: js side:
```js
"./b.module.css": function (module, exports, __webpack_require__) {
module.exports = {
  "b": "_b-module__b---__c156016816e95195-c15" + " " + "_b-module__b-1---___1d9724eea6aa131c-_1d",
  "b-1": "_b-module__b-1---___1d9724eea6aa131c-_1d",
};
},
"./d.module.css": function (module, exports, __webpack_require__) {
module.exports = {
  "d": "_d-module__d---___34b192ed7623f91e-_34" + " " + "_d-module__d-1---__c54e45bb853e1f4b-c54",
  "d-1": "_d-module__d-1---__c54e45bb853e1f4b-c54",
};
},
"./f.module.css": function (module, exports, __webpack_require__) {
module.exports = {
  "f": "_f-module__f---___141af47168767e48-_14" + " " + "_f-module__f-1---___85bca5b4a297a364-_85",
  "f-1": "_f-module__f-1---___85bca5b4a297a364-_85",
};
},
"./style.module.css": function (module, exports, __webpack_require__) {
module.exports = {
  "chain1": "_style-module__chain1---___3a2c0a3269e6f63c-_3a" + " " + "_style-module__chain2---___980d4cb026fb8411-_98" + " " + "c" + " " + __webpack_require__("./d.module.css")["d"] + " " + "e" + " " + __webpack_require__("./f.module.css")["f"],
  "chain2": "_style-module__chain2---___980d4cb026fb8411-_98" + " " + "e" + " " + __webpack_require__("./f.module.css")["f"],
  "root-class": "_style-module__root-class---__aae4264cfe73c127-aae" + " " + "_style-module__chain1---___3a2c0a3269e6f63c-_3a" + " " + "a" + " " + __webpack_require__("./b.module.css")["b"] + " " + "_style-module__chain2---___980d4cb026fb8411-_98" + " " + "c" + " " + __webpack_require__("./d.module.css")["d"] + " " + "e" + " " + __webpack_require__("./f.module.css")["f"],
};
```

I guess we should add snapshot of js side.

**Comment by Thiry1** [comment]
If possible, could you release a canary version for me?

**Comment by h-a-n-a** [comment]
!canary

**Comment by Thiry1** [comment]
Thank you for publish!
I've confirmed that #3875 is fixed.

File: crates/rspack_plugin_css/tests/fixtures/custom/composes/snapshot/output.snap (hunk 2 above)
Comment (h-a-n-a) [reply crates/rspack_plugin_css/tests/fixtures/custom/composes/snapshot/output.snap:1]: Yes, I agree with you. JS part is crucial to make it work.

File: crates/rspack_plugin_javascript/src/ast/stringify.rs (hunk 1 above)
Comment (h-a-n-a) [reply crates/rspack_plugin_javascript/src/ast/stringify.rs:80]: Looks good

File: crates/rspack_plugin_css/tests/fixtures/custom/composes/snapshot/output.snap (hunk 2 above)
Comment (Thiry1) [reply crates/rspack_plugin_css/tests/fixtures/custom/composes/snapshot/output.snap:1]: @h-a-n-a I've added snapshot of js part.
Check it please.

File: crates/rspack_testing/src/run_fixture.rs [hunk 3]
```diff
@@ -37,7 +37,10 @@ pub async fn test_fixture_js(fixture_path: &Path) -> Compiler<AsyncNativeFileSys
 }
 #[tokio::main]
 pub async fn test_fixture_css(fixture_path: &Path) -> Compiler<AsyncNativeFileSystem> {
-  test_fixture_share(fixture_path, &|s| s.ends_with(".css")).await
+  test_fixture_share(fixture_path, &|s| {
+    s.ends_with(".css") || (s.ends_with(".js") && !s.contains("runtime.js"))
```
Comment (h-a-n-a) [inline crates/rspack_testing/src/run_fixture.rs:41]: Maybe we should create a new one exclusively for css module test instead of changing this. I will optimize this once this PR is merged.

**Comment by h-a-n-a** [comment]
Thank you for the contribution!

**Review by h-a-n-a — APPROVED** [review]
