### PR TITLE
fix: the attribute values of HTML tags should not be converted to lowercase

### LINKED ISSUE #8410: [Bug]: Incorrect html output when using compilation hooks and upper case letters in asset file names
### System Info

<details>

<summary>System Info</summary>

```
  System:
    OS: macOS 15.0
    CPU: (11) arm64 Apple M3 Pro
    Memory: 57.17 MB / 18.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 20.15.0 - ~/.anyenv/envs/nodenv/versions/20.15.0/bin/node
    Yarn: 1.22.22 - ~/.anyenv/envs/nodenv/versions/20.15.0/bin/yarn
    npm: 10.7.0 - ~/.anyenv/envs/nodenv/versions/20.15.0/bin/npm
    pnpm: 9.12.3 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 130.0.6723.117
    Edge: 130.0.2849.80
    Safari: 18.0
  npmPackages:
    @rspack/cli: ^1.1.0 => 1.1.0 
    @rspack/core: ^1.1.0 => 1.1.0 
    @rspack/plugin-react-refresh: 1.0.0 => 1.0.0 
```

</details>

### Details

when not using hooks (valid):

```html
<script src="/fooBar.js"></script>
```

when using hooks (invalid):

```html
<script src="/foobar.js"></script><!-- 404 -->
```

This could be the cause:
https://github.com/web-infra-dev/rspack/blob/17e1e38a9b6b026940e704a14de42f496266cbfd/crates/rspack_binding_values/src/html.rs#L59

### Reproduce link

_No response_

### Reproduce Steps

Create a rspack project to output assets that contain uppercase letters, e.g.:
```ts
{
  entry: {
    foorBar: "./src/main.js",
  },
}
```
and add  plugin includes `rspack.HtmlRspackPlugin` hooks
https://rspack.dev/blog/announcing-1-1#improved-html-plugin

### PR DESCRIPTION
**Pull request by inottn**
## Summary

fix #8410

In fact, attr_name should not be converted to lowercase either, as this is the job of the minifier. However, it seems that swc_html_minifier currently does not support the caseSensitive configuration.

## Checklist

- [x] Tests updated (or not required).
- [x] Documentation updated (or not required).

### CODE REVIEW

File: packages/rspack-test-tools/tests/configCases/builtins/html-issue-8410/index.js [hunk 1]
```diff
@@ -0,0 +1,9 @@
+const fs = require("fs");
+const path = require("path");
+
+it("html plugin should respect output.publicPath", () => {
+	const htmlPath = path.join(__dirname, "./index.html");
+	const htmlContent = fs.readFileSync(htmlPath, "utf-8");
+	console.log(htmlContent);
```
Comment (LingyuCoder) [inline packages/rspack-test-tools/tests/configCases/builtins/html-issue-8410/index.js:7]: LGTM, should remove this `console.log` and then it can be merged

Comment (inottn) [reply packages/rspack-test-tools/tests/configCases/builtins/html-issue-8410/index.js]: done

**Review by LingyuCoder — APPROVED** [review]
Thanks
