### PR TITLE
fix: should forward sourcemaps for refresh loaders

### LINKED ISSUE #7870: [Bug]: v1.0.4 generates wrong source maps in development
### System Info

System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 18.35 GB / 31.69 GB
  Binaries:
    Node: 20.14.0 - ~\AppData\Local\Volta\tools\image\node\20.14.0\node.EXE
    Yarn: 3.6.1 - ~\AppData\Local\Volta\tools\image\yarn\3.6.1\bin\yarn.CMD
    npm: 10.7.0 - ~\AppData\Local\Volta\tools\image\node\20.14.0\npm.CMD
    pnpm: 9.10.0 - ~\AppData\Local\Volta\bin\pnpm.EXE
    bun: 1.1.24 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (127.0.2651.98)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @rspack/core: ^1.0.4 => 1.0.4

### Details

Since `@rspack/core@1.0.4` broken sourceMaps are created

Similar bug as [#7535](https://github.com/web-infra-dev/rspack/issues/7535)

output:
image

### Reproduce link

_No response_

### Reproduce Steps

1. create project with `pnpm create rsbuild@latest` 
  - `pnpm run dev`
  - broken source maps
2. create project with `pnpm create rsbuild@1.0.1` or downgrade to `@rsbuild/core@1.0.1` and `@rspack/core@1.0.3` 
  - `pnpm run dev`
  - works

enabling source-map in config works in `build` mode but not in `dev`
```ts
import { defineConfig } from '@rsbuild/core';
import { pluginReact } from '@rsbuild/plugin-react';

export default defineConfig({
  output: {
    sourceMap: {
      js: 'source-map',
    }
  },
  // OR
  // tools: {
  //   rspack: {
  //     devtool: 'source-map',
  //   },
  // },
  plugins: [pluginReact()],
});
```

### PR DESCRIPTION
**Pull request by h-a-n-a**
## Summary

closes #7870

## Checklist

- [X] Tests updated (or not required).
- [ ] Documentation updated (or **not required**).

### CODE REVIEW

File: crates/rspack_loader_preact_refresh/src/lib.rs [hunk 1]
```diff
@@ -27,13 +27,14 @@ impl PreactRefreshLoader {
...
   async fn run(&self, loader_context: &mut LoaderContext<RunnerContext>) -> Result<()> {
-    let content = loader_context
-      .take_content()
-      .expect("Content should be available");
+    let Some(content) = loader_context.take_content() else {
+      return Ok(());
+    };
     let mut source = content.try_into_string()?;
     source += "\n";
     source += include_str!("runtime.js");
```
Comment (SyMind) [inline crates/rspack_loader_preact_refresh/src/lib.rs:35]: Enhanced string concatenation for improved performance. For detailed benchmarks and alternative methods, refer to: [Hoodie's String Concatenation Benchmarks](https://github.com/hoodie/concatenation_benchmarks-rs)

Comment (h-a-n-a) [reply crates/rspack_loader_preact_refresh/src/lib.rs:35]: It's out of the scope of current PR. But you can create an issue though.

**Review by SyMind — APPROVED** [review]
