### PR TITLE
fix: bump version

### LINKED ISSUE #2495: [Bug Report]: swc css parse warning for legacy_ie
### System Info

/

### Details

img_v2_1d8a41da-99a4-4878-aa85-d30767c9dd1g

https://github.com/swc-project/swc/pull/7109#discussion_r1144723279

### Reproduce link

_No response_

### Reproduce Steps

/

### LINKED ISSUE #2497: fix problems of upgrade swc

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
## Summary
1. Main change is pass `es_version` from `options.target` into `swc_compat`, this make `compat_by_es_version` visitor nomore `noop`.

## Related issue (if exists)
1. fixed #2497
2. fixed #2495

## Types of changes

- [ ] Docs change / Dependency upgrade
- [ ] Bug fix
- [ ] New feature / Improvement
- [ ] Refactoring
- [ ] Breaking change

## Checklist

- [ ] I have added changeset via `pnpm run changeset`.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: packages/rspack/tests/configCases/less-loader/additional-data-async-fn/index.js [hunk 1]
```diff
@@ -5,5 +5,5 @@ it("should work as string", () => {
 	require("./index.less");
 	const css = fs.readFileSync(path.resolve(__dirname, "main.css"), "utf-8");
 	expect(css.includes("coral")).toBe(true);
-	expect(css.includes(`relative-path: "index.less"`)).toBe(true);
+	expect(css.includes(`relative-path: 'index.less'`)).toBe(true);
```
Comment (IWANABETHATGUY) [inline packages/rspack/tests/configCases/less-loader/additional-data-async-fn/index.js:8]: I think this is came from bumping the `swc_css`

File: crates/rspack_plugin_javascript/src/visitors/swc_visitor/typescript.rs [hunk 2]
```diff
@@ -33,7 +33,6 @@ pub fn typescript<'a>(
         treat_const_enum_as_enum: false,
         ts_enum_is_readonly: assumptions.ts_enum_is_readonly,
       },
-      use_define_for_class_fields: !assumptions.set_public_class_fields,
```
Comment (IWANABETHATGUY) [inline crates/rspack_plugin_javascript/src/visitors/swc_visitor/typescript.rs:36]: removed since it is deprecated by the latest swc. for more details, you could refer https://github.com/swc-project/swc/issues/7085

File: crates/rspack_plugin_javascript/src/visitors/swc_visitor/react.rs [hunk 3]
```diff
@@ -33,8 +33,6 @@ pub fn react<'a>(
       pragma_frag: options.pragma_frag.clone(),
       throw_if_namespace: options.throw_if_namespace,
       development: options.development,
-      use_builtins: options.use_builtins,
```
Comment (IWANABETHATGUY) [inline crates/rspack_plugin_javascript/src/visitors/swc_visitor/react.rs:36]: removed, since they are deprecated in the latest swc.

File: crates/rspack_plugin_javascript/src/visitors/mod.rs [hunk 4]
```diff
@@ -140,9 +150,10 @@ pub fn run_before_pass(
       // enable if configurable
       // swc_visitor::json_parse(min_cost),
       swc_visitor::paren_remover(comments.map(|v| v as &dyn Comments)),
+      // es_version
       swc_visitor::compat(
         options.builtins.preset_env.clone(),
-        None,
+        es_version,
```
Comment (IWANABETHATGUY) [inline crates/rspack_plugin_javascript/src/visitors/mod.rs:156]: before https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_plugin_javascript/src/visitors/swc_visitor/compat.rs#LL53C41-L53C41, ` compat_by_es_version` never run, because `es_version` is always `None`

File: packages/rspack/tests/configCases/warnings/css-error-tolerate/index.css
Comment (IWANABETHATGUY) [inline packages/rspack/tests/configCases/warnings/css-error-tolerate/index.css:1]: remove this dir, because we will not emit any warning encounter IE legacy filter syntax.

**Review by ahabhgk — APPROVED** [review]

**Review by jerrykingxyz — APPROVED** [review]
