### PR TITLE
fix: mark import.meta.webpackHot type as optional

### LINKED ISSUE #11631: [Feature]: Mark import.meta.webpackHot type signature as optional
### What problem does this feature solve?

Currently, when referencing `@rsbuild/core/types`, ImportMeta type is 
``` ts
interface ImportMeta {
    url: string;
    // TODO: unsupported
    // webpack: number;
    webpackHot: Rspack.Hot;
   // ...
}
```

Cann we make webpackHot be optional, so that it matches the documentation that it may not necessarily exist? (If I got it right, during SSR it does not exist, if this is not expected I'll fire a bug report)
https://rspack.rs/api/runtime-api/hmr#example

### What does the proposed API look like?

-

### PR DESCRIPTION
**Pull request by yf-yang**
## Summary

closes #11631

## Checklist

- [x] Tests updated (or not required).
- [x] Documentation updated (or not required).

### CODE REVIEW

File: packages/rspack/module.d.ts [hunk 1]
```diff
@@ -219,7 +219,7 @@ interface ImportMeta {
 	url: string;
 	// TODO: unsupported
 	// webpack: number;
-	webpackHot: Rspack.Hot;
+	webpackHot?: Rspack.Hot | undefined;
```
Comment (chenjiahan) [inline packages/rspack/module.d.ts]:
```suggestion
	webpackHot?: Rspack.Hot;
```

**Comment by yf-yang** [comment]
Would you like to update this line, too?

https://github.com/web-infra-dev/rspack/blob/9dd9d3d07ca7a9eeaeae612c8b81d48ea3298054/packages/rspack/module.d.ts#L180

**Comment by chenjiahan** [comment]
> Would you like to update this line, too?
> 
> https://github.com/web-infra-dev/rspack/blob/9dd9d3d07ca7a9eeaeae612c8b81d48ea3298054/packages/rspack/module.d.ts#L180

That would be great
