### PR TITLE
fix: fix `this` in ctor default param transform into `undefined`

### LINKED ISSUE #5786: [Bug]: `this` in constructor default parameters resolves to `undefined`
### System Info

```plain
System:
  OS: macOS 14.0
  CPU: (8) arm64 Apple M1
  Memory: 95.02 MB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
  Yarn: 1.22.21 - ~/.nvm/versions/node/v20.9.0/bin/yarn
  npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
  pnpm: 8.15.4 - ~/.nvm/versions/node/v20.9.0/bin/pnpm
Browsers:
  Chrome: 122.0.6261.69
  Safari: 17.0
npmPackages:
  @rspack/cli: ^0.5.4 => 0.5.4 
  @rspack/core: ^0.5.4 => 0.5.4
```

### Details

In the case below

```javascript
class A {
  constructor(func = () => { this.a = 1 }) {}
}
```

rspack with `javascript/esm` will transform it into

```javascript
(function() {
var __webpack_modules__ = {
"./src/test.js": (function (__unused_webpack___webpack_module__, __webpack_exports__, __webpack_require__) {
"use strict";
__webpack_require__.r(__webpack_exports__);
class A {
    constructor(func = ()=>{
        undefined.a = 1;
    }){}
}
}),

}
```

The `this` here becomes `undefined`

I'd like to submit a PR for this issue :eyes:

### Reproduce link

https://github.com/NotEvenANeko/rspack-reproducible

### Reproduce Steps

1. clone the repo
2. run `pnpm i && pnpm build`
3. check `dist/main.js`, `this` turns into `undefined` here.

### PR DESCRIPTION
**Pull request by NotEvenANeko**
## Summary

Fix #5786 

## Require Documentation?

- [x] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by bvanjoi** [comment]
I think the ﻿`index.js` in the test case should be as follows:

```js
class A {
  constructor(func = () => { this.a = 1 }) {
		func()
	}
}

it('ensure top level is right in constructor', () => {
	const a = new A();
	expect(a.a).toBe(1)
	expect(typeof a).toBe('object')
}) 

export default '';
```

**Comment by NotEvenANeko** [comment]
Added

File: packages/rspack/tests/cases/parsing/issue-5786/index.js [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+	) {
+		func();
+	}
+}
+
+it("ensure top level is right in constructor parameters", () => {
+	const a = new A();
+	expect(a.a).toBe(1);
+	expect(typeof a).toBe("object");
+});
```
Comment (bvanjoi) [inline packages/rspack/tests/cases/parsing/issue-5786/index.js:15]: The inclusion of ﻿`export default ''` is necessary as it allows this file to be recognized as `﻿js/esm` instead of `﻿js/auto`.

**Review by bvanjoi — CHANGES_REQUESTED** [review]

**Review by bvanjoi — APPROVED** [review]

**Comment by bvanjoi** [comment]
Thanks!
