### PR TITLE
fix(plugin/swc_js_minimizer): remove parens before optimizing

### LINKED ISSUE #5656: [Bug]: "asset/resource"  module used to handle ".lottie"-animations works in dev-mode but breaks animation-file in production mode
### System Info

System:
OS: macOS 14.2.1,
CPU: Apple M2 pro
Memory: 16gb
Shell: 5.9 - /bin/zsh
Binaries:
Node: 20.10.0
npm: 10.2.3
Browsers:
Chrome 121.0.6167.160
Safari 17.2.1
npmPackages:
@rspack/cli: 0.5.4
@rspack/core:  0.5.4
@dotlottie/player-component: 1.3.2
react: 18.2.0
react-dom: 18.2.0

### Details

To handle import of animations (".lottie"-files ) in my app i use builtin "asset/resource" module. This works great in development mode and all animations are imported correctly. However when I switch to production mode, all imported animations break and can not be loaded correctly. If i switch to webpack 5 (version 5.89.0) all files are loaded correctly in both production and development mode. 

### Reproduce link

_No response_

### Reproduce Steps

1. setup "asset/resource" to handle ".lottie" files  in rspack.config
2. set mode to "production" in rspack.config
3. import a ".dotlottie"-file to dot-lottie-player from @dotlottie/player-component
5.  animation wont work
6. switch to development mode in  rspack.config
7. animation will work

### PR DESCRIPTION
**Pull request by magic-akari**
## Summary

The function `paren_remover` is required for `swc_ecma_minifier::optimize`.

- Fix: #5656 

## Require Documentation?

- [x] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

### CODE REVIEW

**Comment by xc2** [comment]
have tried this change - [rspack-lottie-1.0.0.tgz](https://github.com/web-infra-dev/rspack/files/14341358/rspack-lottie-1.0.0.tgz) works well with it

File: packages/rspack/tests/copyPlugin/build/main.js [hunk 1]
```diff
@@ -1 +1 @@
...
\ No newline at end of file
+!function(){var t={435:function(t,e,r){"use strict";r.r(e);var o=r("287");e.default=o},287:function(t,e,r){"use strict";t.exports=r.p+"asset-modules/deepnested.txt"}},e={};function r(o){var n=e[o];if(void 0!==n)return n.exports;var i=e[o]={exports:{}};return t[o](i,i.exports,r),i.exports}r.r=function(t){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(t,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(t,"__esModule",{value:!0})},r.g=function(){if("object"==typeof globalThis)return globalThis;try{return this||Function("return this")()}catch(t){if("object"==typeof window)return window}}(),!function(){r.g.importScripts&&(t=r.g.location+"");var t,e=r.g.document;if(!t&&e&&(e.currentScript&&(t=e.currentScript.src),!t)){var o=e.getElementsByTagName("script");if(o.length){for(var n=o.length-1;n>-1&&!t;)t=o[n--].src}}if(!t)throw Error("Automatic publicPath is not supported in this browser");t=t.replace(/#.*$/,"").replace(/\?.*$/,"").replace(/\/[^\/]+$/,"/"),r.p=t}(),r("435")}();
```
Comment (hardfist) [inline packages/rspack/tests/copyPlugin/build/main.js:1]: this seems change the value of iife？

Comment (magic-akari) [reply packages/rspack/tests/copyPlugin/build/main.js:1]: This is a bugfix. 
Previously, due to the absence of a parenthesis remover, many assumptions within the minifier were invalid. 
After fixing the bug, more minifier rules are applied. 

In this case, the return value of the IIFE is not used, and this transformation only occurs under this condition.

Comment (hardfist) [reply packages/rspack/tests/copyPlugin/build/main.js:1]: it will cause problem when the code is eval scenario, so is a swc option like  negate_iife in terser to control this behavior?

Comment (magic-akari) [reply packages/rspack/tests/copyPlugin/build/main.js:1]: > is a swc option like negate_iife in terser to control this behavior?

Yes.

With [negate_iife: true](https://play.swc.rs/?version=1.4.2&code=H4sIAAAAAAAAA9NIK81LLsnMz1NIy8%2FX0FSo5lIAgrT8IgWNCmsFEIKJ1XLVampoAgB7VYOLMAAAAA%3D%3D&config=H4sIAAAAAAAAA12PSw6DMAxE95wCed1FlUUXvUPPUFmpQanIR7GRihB3rwmBom6i%2BGVmPJmbtoU3W7i3s151SJiZ8jEr4SkIfpQAWY9ss0sC5XG5bB7B3JMUBZurMVD5ECOT4g4Hpsq8C66bzvkeQz%2F8yRTb6FMm5pNUaaAehZ7OdatD8ngYlmY%2FSy3w8TWW2PoxmRJtFW%2FwE%2B1tjt3g%2BLE71%2Fhm%2BQJkYWsMJAEAAA%3D%3D)
With [negate_iife: false](https://play.swc.rs/?version=1.4.2&code=H4sIAAAAAAAAA9NIK81LLsnMz1NIy8%2FX0FSo5lIAgrT8IgWNCmsFEIKJ1XLVampoAgB7VYOLMAAAAA%3D%3D&config=H4sIAAAAAAAAA12PPQrDMAyF95zCaO5QPHToHXqGIlwluMQ%2FWAo0hNy9wnHS0EVIn96Tn5fOGHizg7tZtNUhY2Eqx6yE5yj4UQLkArIrPgvU5XrZPIJlIKkKtldrofExJSbFPY5MjQUffT%2Bf7weMw%2FgnU%2BxSyIWYT1KlkQYUenrfH462XLu91lgQ0muqZ9vHZM60RbzBT7SnOd4Gz4%2FdKWWibv0C5z49jyQBAAA%3D)

Comment (hardfist) [reply packages/rspack/tests/copyPlugin/build/main.js:1]: then it's fine

**Review by hardfist — APPROVED** [review]
